### ISSUE TITLE
Allow [authenticated] user to view detailed deal.

### ISSUE THREAD

**Issue by GerryAgbay** [KandarpAjvalia/tabledeals#16]
As a user, I should be able to view detailed restaurant deals, so that I can make an informed decision about where to eat.
● A search bar for restaurant/bar deal posts appears on the home page.
● Search results will display only deal posts, but users can filter by restaurants.
● Clicking on the deal post brings me to a page with detailed information about the
searched deal post.
● This page contains the restaurant’s name, address, time, and what type of food the
restaurant sells.
● The deal detail page also shows upvote/downvote, and add comment for deal to
authenticated users.

**Comment by KandarpAjvalia** [comment]
does the user need to be logged in to see the detailed page? I think we can allow anyone to view the deal detail page, what are your thoughts?

**Comment by benjam9** [comment]
@KandarpAjvalia Yeah I was thinking that too, I feel like users might get annoyed if they have to sign in to see extra info

**Comment by KandarpAjvalia** [comment]
Let's keep it simple then
