### ISSUE TITLE
Detailed Filters

### ISSUE THREAD

**Issue by benjam9** [KandarpAjvalia/tabledeals#31]
- I should be able to filter deals so that I am viewing more specific categories of food or drink. 
- The filter menu on the left of the deals page will have more detailed filter options in dropdown menus under the food/drink filters.
- I should be able to select filters so that the deals I see only include food of the type I pick. (vegetarian, vegan, etc.)
- I should be able to select filters so that the deals I see only include drink of the type I pick. (beer, wine, liquor, etc.)

**Comment by KandarpAjvalia** [comment]
hey, can we update this user story? we can add additional filters ex: food -> vegetarian, vegan, different cuisines; drink -> beer, wine, liquor
